# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Uguu 
tagline:          'A Jekyll theme'
description:      'The magnificent stories of kawaii computing by <a href="https://twitter.com/RadoslawKujawa" target="_blank">@RadoslawKujawa</a>.'
url: 		  http://blog.uguu.waw.pl/
baseurl: 	  http://blog.uguu.waw.pl/

author:
  name:           'Radoslaw Kujawa'
  url:            https://c0ff33.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rkujawa/blog

